# Generated by Django 4.0.2 on 2023-01-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='prayertime__usernam_1e0b45_idx'),
        ),
    ]
