# Generated by Django 4.0.2 on 2023-02-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='city',
        ),
    ]
