# Generated by Django 4.0.2 on 2023-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0002_rename_address_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='admin_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
