# Generated by Django 4.0.2 on 2023-01-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0003_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send',
            name='total',
        ),
    ]
