# Generated by Django 4.0.2 on 2023-01-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0004_remove_send_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('kun', models.DateTimeField()),
                ('tong', models.DateTimeField()),
                ('quyosh', models.DateTimeField()),
                ('pewn', models.DateTimeField()),
                ('asr', models.DateTimeField()),
                ('shom', models.DateTimeField()),
                ('xufton', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.AddIndex(
            model_name='time',
            index=models.Index(fields=['city'], name='prayertime__city_49b1c4_idx'),
        ),
    ]
