# Generated by Django 4.0.2 on 2023-01-27 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0005_time_time_prayertime__city_49b1c4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='update_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
