# Generated by Django 4.0.2 on 2023-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0007_alter_time_asr_alter_time_city_alter_time_kun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='created_time',
            field=models.TimeField(blank=True, null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
