# Generated by Django 4.0.2 on 2023-01-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0011_alter_time_asr_alter_time_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='city_id',
            field=models.IntegerField(default=0),
        ),
    ]
