# Generated by Django 4.0.2 on 2023-01-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0012_time_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='created_time',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
