# Generated by Django 4.0.2 on 2023-01-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0013_rename_created_time_time_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='updated_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
