# Generated by Django 4.0.2 on 2023-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0014_alter_time_updated_date_alter_time_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
