# Generated by Django 4.0.2 on 2023-01-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0015_alter_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
