# Generated by Django 4.0.2 on 2023-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0016_alter_time_updated_date_alter_time_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='kun',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
