# Generated by Django 4.0.2 on 2023-01-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0017_alter_time_kun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='pewn',
            new_name='peshin',
        ),
    ]
