# Generated by Django 4.0.2 on 2023-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertime', '0018_rename_pewn_time_peshin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='updated_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
